apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-service
  template:
    metadata:
      labels:
        app: oauth-service
    spec:
      containers:
        - name: oauth-service
          # Change the image to the according one
          image: docker.io/jsovalles/oauth-service:latest
          ports:
            - containerPort: 8080
