version: '3.8'

services:
  db:
    image: postgres:15.2-alpine3.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql